name: push_Groupe8

on:
  push:
    branches: [ "main" ]

jobs:
  hello_Groupe8:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4ll
      - name: Dit Hello
        run: echo Hello, CI!
