name: Matrix_Branches_Groupe8

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_Groupe8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Cache Node modules
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: |
          mkdir dist
          echo "Build complet matriciel" > dist/index.html

      # L'artefact servira au déploiement
      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: matrix-build-Groupe8
          path: dist/

  test_Groupe8:
    needs: build_Groupe8
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22, 24] # Exécution en parallèle sur les deux versions
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node modules
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy_Groupe8:
    needs: test_Groupe8
    if: github.ref == 'refs/heads/main' # Condition stricte : uniquement sur main
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v5
        with:
          name: matrix-build-Groupe8
          path: dist/

      - name: Deploy Production
        run: echo "Déploiement en production réussi pour le Groupe8 !"
